Vagrant.configure("2") do |config|
  config.vm.box = "chef/centos-7.0"

  config.vm.synced_folder "/apps", "/apps"
  config.vm.synced_folder "defaults", "/defaults"
  
  config.vm.synced_folder "/apps/git/wufoo-connector/target", "/webapps"

  config.vm.network :forwarded_port, host:4545, guest:8080

  config.vm.provision :shell, path: "install_jdk.sh"
  config.vm.provision :shell, path: "install_tomcat.sh"
  config.vm.provision :shell, path: "config_start.sh"

end
